{% set name = "exact-real" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/flatsurf/exact-real/releases/download/{{ version }}/exact-real-{{ version }}.tar.gz
  sha256: 02cfef7aa18c316bafaf0d80163dc3d1bc25c804bf862d86353cde656931e0c3

build:
  number: 5
  # dependency libeantic is not available for Windows on conda-forge yet
  skip: true  # [win]

outputs:
  - name: libexactreal
    script: build-libexactreal.sh  # [not win]
    script: build-libexactreal.bat  # [win]
    run_exports:
      - {{ pin_subpackage("libexactreal") }}
    requirements:
      build:
        - libtool   # [unix]
        - automake  # [unix]
        - make      # [unix]
        - autotools_clang_conda  # [win]
        - gnuconfig  # [unix]
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
      host:
        - libflint
        # We only need the libboost-headers at compile time. However, since we
        # use bits of boost in our API, code built against libexactreal must be
        # built with a compatible version of the headers. Therefore, we add a
        # liboost pin to our run exports so libbookst-headers are going to be
        # in a compatible version.
        - libboost-devel
        - libeantic
        - gmp  # [unix]
        - mpir  # [win]
    test:
      commands:
        - test -f $PREFIX/include/exact-real/exact-real.hpp  # [unix]
        - test -f $PREFIX/lib/libexactreal${SHLIB_EXT}                # [unix]
  - name: pyexactreal
    script: build-pyexactreal.sh  # [not win]
    script: bld-pyexactreal.bat  # [win]
    requirements:
      build:
        - python                              # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - libtool   # [unix]
        - automake  # [unix]
        - make      # [unix]
        - autotools_clang_conda  # [win]
        - gnuconfig  # [unix]
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
      host:
        # Note that the libboost-devel from libexactreal forces these headers to be
        # compatible with ones used when building libexactreal.
        - libboost-headers
        - python
        - cppyy >=3,<4
        - cppyythonizations
        - setuptools
        - pytest
        - {{ pin_subpackage("libexactreal") }}
      run:
        # cppyy dynamically compiles C++ wrappers at runtime, therefore we need C++ headers of boost.
        # Note that the libboost-devel from libexactreal forces these headers to be
        # compatible with ones used when building libexactreal.
        - libboost-headers
        - python
        - cppyy >=3,<4
        - cppyythonizations
        - pyeantic
        - gmpxxyy
        # A subpackage does not see the run_exports of another subpackage:
        # https://github.com/conda/conda-build/issues/3478
        - {{ pin_subpackage("libexactreal") }}
    test:
      imports:
        - pyexactreal

about:
  home: https://github.com/flatsurf/exact-real
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Lazy computations with real numbers in C++ and Python
  description: |
    exact-real is a C++/Python library which provides exact lazy computations
    in the Real Numbers. In particular it provides arithmetic and comparisons
    of (random) transcendental numbers.
  dev_url: https://github.com/flatsurf/exact-real

extra:
  recipe-maintainers:
    - saraedum
